#!/bin/bash
clear
echo “Starting script…”
if [ $# -le 2 ]
then
	echo “Invalid Parameters”
elif [ $# -ge 6 ]
then
	echo “Invalid Parameters”
else 
	echo “Valid range of Parameters, compiling the program…”
	cd p1/src
	echo “Compiling…”
	javac srget.java
	javac ResumableChecker.java
	javac MasterThread.java
	javac WorkerThread.java
	javac ExtendedThreadPool.java
	javac HeadProc.java
	javac Processor.java
	javac ProcessNormal.java
	javac ProcessCTE.java
	echo “Running the program…”
	java srget $@
	echo “Finished running the program…”
	cd ..
	cd ..
fi
echo “Done with script…”
